# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: push

env:
  # GATSBY_S3_BUCKET_NAME is required by a Gatsby plugin
  # when we test the build step.
  GATSBY_S3_BUCKET_NAME: dev-tab-website
  GATSBY_DOMAIN: example.com # used in some tests

# List of jobs
jobs:
  test:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - name: Build
        run: yarn build
        #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          autoAcceptChanges: true
          exitOnceUploaded: true
        env: 
          STORYBOOK_CHROMATIC_ENV: true


