name: Run end-to-end tests

# TODO: change to PR only
on: [push]
# on: [pull_request]

env:
  GATSBY_S3_BUCKET_NAME: test-tab-website
  GATSBY_DOMAIN: test-tab2017.gladly.io
  SHOW_CATS_PAGE: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      # The deploy user needs the following permissions:
      # https://github.com/jariz/gatsby-plugin-s3/issues/39#issuecomment-467379363
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Deploy to test environemnt
        run: yarn run deploy
      # TODO: enable
      # - name: Run end-to-end tests
      #   run: yarn run tests:e2e
