name: Run tests

on: [push, pull_request]

env:
  # GATSBY_S3_BUCKET_NAME is required by a Gatsby plugin
  # when we test the build step.
  GATSBY_S3_BUCKET_NAME: dev-tab-website
  GATSBY_DOMAIN: example.com # used in some tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test # generates coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
      - name: Build
        run: yarn run build # ensure build does not error
